# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Status')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='certmngt.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.URLField(verbose_name='Certificate URL')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3, max_length=7, verbose_name='Priority')),
                ('status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certmngt.Category')),
            ],
        ),
    ]
