# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certmngt', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslcertificate',
            name='certificate_url',
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='save_copy',
            field=models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Save copy'),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
