# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certmngt', '0004_auto_20180308_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.BooleanField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Status')),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certmngt.SSLCertificate')),
            ],
        ),
    ]
